<../../../mkconfig

DISBIN=$ROOT/dis

TARG=\
	parse.dis\
	trackerget.dis\
	get.dis\
	verify.dis\
	info.dis\
	track.dis\

MODULES=\
	../../lib/bittorrent/get.m\

SYSMODULES=\
	arg.m\
	bufio.m\
	bundle.m\
	daytime.m\
	draw.m\
	keyring.m\
	math.m\
	lists.m\
	string.m\
	sys.m\
	tables.m\
	bitarray.m\
	bittorrent.m\

DISBIN=$ROOT/dis/torrent

<$ROOT/mkfiles/mkdis
