<../../../mkconfig

TARG=\
	bittorrent.dis\
	misc.dis\
	pools.dis\
	rate.dis\
	requests.dis\
	peers.dis\
	pieces.dis\
	verify.dis\
	schedule.dis\

MODULES=\
	get.m\
	torrentget.m\

SYSMODULES=\
	bufio.m\
	daytime.m\
	filter.m\
	keyring.m\
	lists.m\
	security.m\
	string.m\
	sys.m\
	bitarray.m\
	bittorrent.m\
	ohttp.m\

DISBIN=$ROOT/dis/lib/bittorrent

<$ROOT/mkfiles/mkdis
